
eureka:
  instance:
    hostname: ${springboot.app.name:Discovery-Service}
    
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/
    
    

server:
   port: 9001